/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.bloodbankAdminRole;

import Business.Blood.BloodDirectory;
import Business.Blood.BloodGroup;
import Business.Blood.BloodSpecs;
import Business.Organization.BloodBankStaffOrganization;
import java.awt.CardLayout;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author mihir
 */
public class BloodDonation extends javax.swing.JPanel {
 private ButtonGroup bg1= new ButtonGroup();
 private int opt;
 private String Bloodgroup;
  JPanel userProcessContainer;
  private  Boolean b;
  private BloodBankStaffOrganization organization;
 /* private BloodGroup bldgrp;
  private BloodSpecs bldsps;
  private BloodDirectory BldDir;*/
    /**
     * Creates new form BloodDonation
     */
    public BloodDonation(JPanel userProcessContainer, BloodBankStaffOrganization organization) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.organization=organization;
          this.b=true;
        /*this.bldgrp=bg ;
        bldsps=new BloodSpecs();
       this.BldDir=blooddir;*/
        groupbutton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        _AjRadioButton1 = new javax.swing.JRadioButton();
        AjRadioButton2 = new javax.swing.JRadioButton();
        _BjRadioButton3 = new javax.swing.JRadioButton();
        BjRadioButton4 = new javax.swing.JRadioButton();
        _OjRadioButton5 = new javax.swing.JRadioButton();
        OjRadioButton6 = new javax.swing.JRadioButton();
        _ABjRadioButton7 = new javax.swing.JRadioButton();
        ABjRadioButton8 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        volTxt = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        bl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("Blood Donation");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setText("Donor Name:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 102));
        jLabel3.setText("Select Blood Group:");

        _AjRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        _AjRadioButton1.setForeground(new java.awt.Color(255, 102, 102));
        _AjRadioButton1.setText("-A");
        _AjRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _AjRadioButton1MouseClicked(evt);
            }
        });
        _AjRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _AjRadioButton1ActionPerformed(evt);
            }
        });

        AjRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AjRadioButton2.setForeground(new java.awt.Color(255, 102, 102));
        AjRadioButton2.setText("+A");
        AjRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AjRadioButton2MouseClicked(evt);
            }
        });
        AjRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjRadioButton2ActionPerformed(evt);
            }
        });

        _BjRadioButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        _BjRadioButton3.setForeground(new java.awt.Color(255, 102, 102));
        _BjRadioButton3.setText("-B");
        _BjRadioButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _BjRadioButton3MouseClicked(evt);
            }
        });

        BjRadioButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BjRadioButton4.setForeground(new java.awt.Color(255, 102, 102));
        BjRadioButton4.setText("+B");
        BjRadioButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BjRadioButton4MouseClicked(evt);
            }
        });

        _OjRadioButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        _OjRadioButton5.setForeground(new java.awt.Color(255, 102, 102));
        _OjRadioButton5.setText("-O");
        _OjRadioButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _OjRadioButton5MouseClicked(evt);
            }
        });

        OjRadioButton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        OjRadioButton6.setForeground(new java.awt.Color(255, 102, 102));
        OjRadioButton6.setText("+O");
        OjRadioButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OjRadioButton6MouseClicked(evt);
            }
        });

        _ABjRadioButton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        _ABjRadioButton7.setForeground(new java.awt.Color(255, 102, 102));
        _ABjRadioButton7.setText("-AB");
        _ABjRadioButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _ABjRadioButton7MouseClicked(evt);
            }
        });

        ABjRadioButton8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ABjRadioButton8.setForeground(new java.awt.Color(255, 102, 102));
        ABjRadioButton8.setText("+AB");
        ABjRadioButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ABjRadioButton8MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 102));
        jLabel4.setText("Volume:");

        nametxt.setColumns(15);
        nametxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nametxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nametxtKeyReleased(evt);
            }
        });

        volTxt.setColumns(7);
        volTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        volTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volTxtActionPerformed(evt);
            }
        });
        volTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                volTxtKeyReleased(evt);
            }
        });

        submitBtn.setBackground(new java.awt.Color(255, 102, 102));
        submitBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        submitBtn.setForeground(new java.awt.Color(255, 255, 255));
        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setText("1 Unit=(350ml)");

        bl.setForeground(new java.awt.Color(255, 51, 51));

        jLabel8.setForeground(new java.awt.Color(255, 51, 51));

        jLabel9.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel2)
                        .addGap(10, 10, 10)
                        .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(6, 6, 6)
                                .addComponent(bl, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(_AjRadioButton1)
                                .addGap(35, 35, 35)
                                .addComponent(AjRadioButton2)
                                .addGap(35, 35, 35)
                                .addComponent(_BjRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(BjRadioButton4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(_OjRadioButton5)
                                .addGap(35, 35, 35)
                                .addComponent(OjRadioButton6)
                                .addGap(35, 35, 35)
                                .addComponent(_ABjRadioButton7)
                                .addGap(35, 35, 35)
                                .addComponent(ABjRadioButton8))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel4)
                                .addGap(35, 35, 35)
                                .addComponent(volTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jButton2)
                        .addGap(81, 81, 81)
                        .addComponent(submitBtn)))
                .addContainerGap(400, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel3))
                    .addComponent(bl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_AjRadioButton1)
                    .addComponent(AjRadioButton2)
                    .addComponent(_BjRadioButton3)
                    .addComponent(BjRadioButton4))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_OjRadioButton5)
                    .addComponent(OjRadioButton6)
                    .addComponent(_ABjRadioButton7)
                    .addComponent(ABjRadioButton8))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(volTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(submitBtn))
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AjRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AjRadioButton2ActionPerformed

    private void _AjRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__AjRadioButton1ActionPerformed
    opt=1;
    
// TODO add your handling code here:
    }//GEN-LAST:event__AjRadioButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
     jLabel8.setText("");
     bl.setText("");
     jLabel9.setText("");
     b=true;
   
    
          if(bg1.getSelection()==null){bl.setText("Select a bloodgroup");
          b=false;
     }
        
        if(nametxt.getText().trim().isEmpty()){
       jLabel9.setText(" Name field is empty");
        b=false;;}
         
         try{int x=Integer.parseInt(volTxt.getText());
         }
         catch(NumberFormatException e){
             jLabel8.setText("Enter valid number");
             b=false;
         }
         if(volTxt.getText().trim().isEmpty()){
           jLabel8.setText("Volume field is empty");
         b=false;}
       if(b){
        int vol=Integer.parseInt(volTxt.getText());
        
        //..............adding blood to stocks..................
             
        if(AjRadioButton2.isSelected()){
           
            int a=organization.getBldgrp().getApositive();
            a=a+vol;
            organization.getBldgrp().setApositive(a);
            Bloodgroup="A+ve";
          
           }
         if(_AjRadioButton1.isSelected()){
           
            int a=organization.getBldgrp().getAnegative();
            a=a+vol;
            organization.getBldgrp().setAnegative(a);
             Bloodgroup="A-ve";
             
           }
         if(_BjRadioButton3.isSelected()){
           
            int a=organization.getBldgrp().getBnegative();
            a=a+vol;
            organization.getBldgrp().setBnegative(a);
            Bloodgroup="B-ve";
          
           }
         if(BjRadioButton4.isSelected()){
           
            int a=organization.getBldgrp().getBpositive();
            a=a+vol;
            organization.getBldgrp().setBpositive(a);
         Bloodgroup="B+ve";
        
           }
        if(_OjRadioButton5.isSelected()){
           
            int a=organization.getBldgrp().getOnegative();
            a=a+vol;
            organization.getBldgrp().setOnegative(a);
             Bloodgroup="O-ve";
            
           }
        if(OjRadioButton6.isSelected()){
           
            int a=organization.getBldgrp().getOpositive();
            a=a+vol;
            organization.getBldgrp().setOpositive(a);
             Bloodgroup="O-ve";
           
           }
          if(_ABjRadioButton7.isSelected()){
           
            int a=organization.getBldgrp().getAbnegative();
            a=a+vol;
            organization.getBldgrp().setAbnegative(a);
             Bloodgroup="AB-ve";
             
           }
          if(ABjRadioButton8.isSelected()){
           
            int a=organization.getBldgrp().getABpositive();
            a=a+vol;
            organization.getBldgrp().setABpositive(a);
             Bloodgroup="AB+ve";
            
            }
          
          
        
           
        
            String Name=nametxt.getText();
            BloodSpecs blood=organization.getBlddir().CreateBloodSpec(Name, Bloodgroup, vol);
            JOptionPane.showMessageDialog(null,"Successfully added to records!");
     
       }
         
        
        
    //    CreateBloodSpec(Name, BloodGroup,vol);
        // TODO add your handling code here:
    }//GEN-LAST:event_submitBtnActionPerformed

    private void nametxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nametxtKeyReleased
         jLabel9.setText("");
        if(nametxt.getText().trim().isEmpty()){
       jLabel9.setText(" Name field is empty");
        b=false;;} // TODO add your handling code here:
    }//GEN-LAST:event_nametxtKeyReleased

    private void volTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_volTxtKeyReleased
        jLabel8.setText(""); 
        try{int x=Integer.parseInt(volTxt.getText());
         }
         catch(NumberFormatException e){
             jLabel8.setText("Enter valid number");
             b=false;
         }
             if(volTxt.getText().trim().isEmpty()){
           jLabel8.setText("Volume field is empty");
         b=false;}
// TODO add your handling code here:
    }//GEN-LAST:event_volTxtKeyReleased

    private void _BjRadioButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__BjRadioButton3MouseClicked
 bl.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event__BjRadioButton3MouseClicked

    private void _AjRadioButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__AjRadioButton1MouseClicked
 bl.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event__AjRadioButton1MouseClicked

    private void AjRadioButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AjRadioButton2MouseClicked
 bl.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_AjRadioButton2MouseClicked

    private void BjRadioButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BjRadioButton4MouseClicked
 bl.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_BjRadioButton4MouseClicked

    private void _OjRadioButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__OjRadioButton5MouseClicked
 bl.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event__OjRadioButton5MouseClicked

    private void OjRadioButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OjRadioButton6MouseClicked
 bl.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_OjRadioButton6MouseClicked

    private void _ABjRadioButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__ABjRadioButton7MouseClicked
 bl.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event__ABjRadioButton7MouseClicked

    private void ABjRadioButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ABjRadioButton8MouseClicked
 bl.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_ABjRadioButton8MouseClicked

    private void volTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_volTxtActionPerformed
public void groupbutton(){
   // ButtonGroup bg1= new ButtonGroup();
        ABjRadioButton8.setActionCommand("ABjRadioButton8");
    bg1.add(ABjRadioButton8);
   AjRadioButton2.setActionCommand("AjRadioButton2");
    bg1.add(AjRadioButton2);
    
    BjRadioButton4.setActionCommand("BjRadioButton4");
    bg1.add(BjRadioButton4);
    
    OjRadioButton6.setActionCommand("OjRadioButton6");
    bg1.add(OjRadioButton6);
    
    _ABjRadioButton7.setActionCommand("_ABjRadioButton7");
    bg1.add(_ABjRadioButton7);
    
    _AjRadioButton1.setActionCommand("_AjRadioButton1");
    bg1.add(_AjRadioButton1);
    
    _BjRadioButton3.setActionCommand("_BjRadioButton3");
    bg1.add(_BjRadioButton3);
    
    _OjRadioButton5.setActionCommand("_OjRadioButton5");
    bg1.add(_OjRadioButton5);
   // btnsel = String.valueOf(bg1.getSelection());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ABjRadioButton8;
    private javax.swing.JRadioButton AjRadioButton2;
    private javax.swing.JRadioButton BjRadioButton4;
    private javax.swing.JRadioButton OjRadioButton6;
    private javax.swing.JRadioButton _ABjRadioButton7;
    private javax.swing.JRadioButton _AjRadioButton1;
    private javax.swing.JRadioButton _BjRadioButton3;
    private javax.swing.JRadioButton _OjRadioButton5;
    private javax.swing.JLabel bl;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nametxt;
    private javax.swing.JButton submitBtn;
    private javax.swing.JTextField volTxt;
    // End of variables declaration//GEN-END:variables
}
