/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ManagerRole;

import Business.BloodBankWorkQueue.BloodbankWorkRequest;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.BloodBankStaffOrganization;
import Business.Organization.LabOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author mihir
 */
public class ProcessBloodRequest extends javax.swing.JPanel {
      private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem system;
    private ButtonGroup bg1=new ButtonGroup();
    private Boolean b;
    
    /**
     * Creates new form ProcessBloodRequest
     */
    public ProcessBloodRequest(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.system=system;
        this.b=true;
      
        groupbutton();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        ABjRadioButton8 = new javax.swing.JRadioButton();
        _ABjRadioButton7 = new javax.swing.JRadioButton();
        submitBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        _AjRadioButton1 = new javax.swing.JRadioButton();
        volTxt = new javax.swing.JTextField();
        AjRadioButton2 = new javax.swing.JRadioButton();
        _BjRadioButton3 = new javax.swing.JRadioButton();
        BjRadioButton4 = new javax.swing.JRadioButton();
        _OjRadioButton5 = new javax.swing.JRadioButton();
        OjRadioButton6 = new javax.swing.JRadioButton();
        volLabl = new javax.swing.JLabel();
        bldLbl1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 102));
        jLabel4.setText("Volume:");

        ABjRadioButton8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ABjRadioButton8.setForeground(new java.awt.Color(255, 102, 102));
        ABjRadioButton8.setText("+AB");

        _ABjRadioButton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        _ABjRadioButton7.setForeground(new java.awt.Color(255, 102, 102));
        _ABjRadioButton7.setText("-AB");

        submitBtn.setBackground(new java.awt.Color(255, 102, 102));
        submitBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        submitBtn.setForeground(new java.awt.Color(255, 255, 255));
        submitBtn.setText("SUBMIT");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 102));
        jLabel3.setText("Select Blood Group:");

        _AjRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        _AjRadioButton1.setForeground(new java.awt.Color(255, 102, 102));
        _AjRadioButton1.setText("-A");
        _AjRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _AjRadioButton1ActionPerformed(evt);
            }
        });

        volTxt.setColumns(7);
        volTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        volTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                volTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                volTxtKeyReleased(evt);
            }
        });

        AjRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AjRadioButton2.setForeground(new java.awt.Color(255, 102, 102));
        AjRadioButton2.setText("+A");
        AjRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjRadioButton2ActionPerformed(evt);
            }
        });

        _BjRadioButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        _BjRadioButton3.setForeground(new java.awt.Color(255, 102, 102));
        _BjRadioButton3.setText("-B");

        BjRadioButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BjRadioButton4.setForeground(new java.awt.Color(255, 102, 102));
        BjRadioButton4.setText("+B");

        _OjRadioButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        _OjRadioButton5.setForeground(new java.awt.Color(255, 102, 102));
        _OjRadioButton5.setText("-O");

        OjRadioButton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        OjRadioButton6.setForeground(new java.awt.Color(255, 102, 102));
        OjRadioButton6.setText("+O");

        volLabl.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        volLabl.setForeground(new java.awt.Color(255, 0, 0));

        bldLbl1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        bldLbl1.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(185, 185, 185)
                                .addComponent(submitBtn))
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(_OjRadioButton5)
                                    .addComponent(_AjRadioButton1))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(OjRadioButton6))
                                    .addComponent(AjRadioButton2))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(_ABjRadioButton7)
                                    .addComponent(_BjRadioButton3))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BjRadioButton4)
                                    .addComponent(ABjRadioButton8)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(35, 35, 35)
                                .addComponent(volTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bldLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(volLabl, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel3)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bldLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(_AjRadioButton1)
                                        .addComponent(AjRadioButton2))
                                    .addGap(15, 15, 15)
                                    .addComponent(_OjRadioButton5))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(OjRadioButton6)
                                    .addComponent(_ABjRadioButton7)
                                    .addComponent(ABjRadioButton8)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(_BjRadioButton3)
                                .addComponent(BjRadioButton4)))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(volTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(volLabl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitBtn)
                    .addComponent(jButton2))
                .addContainerGap(130, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
      volLabl.setText(""); 
      bldLbl1.setText("");
      
        
       b =true;
        try{
            int v=Integer.parseInt(volTxt.getText());}
        catch(NumberFormatException e){
              b=false;
              volLabl.setText("Enter a valid integer");
            }
          if(volTxt.getText().trim().isEmpty()){
       volLabl.setText(" Volumefield is empty");
        b=false;;}
        if(bg1.getSelection()==null){
          b=false;
              bldLbl1.setText("Select blood group");}
        if(b){
        int vol=Integer.parseInt(volTxt.getText());
       BloodbankWorkRequest req= new BloodbankWorkRequest();
        req.setVolume(vol);
        //..............adding blood to stocks..................
        if(AjRadioButton2.isSelected()){
            req.setBloodGroup("A+ve");
        }
        if(_AjRadioButton1.isSelected()){
            req.setBloodGroup("A-ve");
        }
        if(_BjRadioButton3.isSelected()){
            req.setBloodGroup("B-ve");
        }
        if(BjRadioButton4.isSelected()){
            req.setBloodGroup("B+ve");
        }
        if(_OjRadioButton5.isSelected()){
            req.setBloodGroup("O-ve");
        }
        if(OjRadioButton6.isSelected()){
        req.setBloodGroup("O+ve");
        }
        if(_ABjRadioButton7.isSelected()){
        req.setBloodGroup("AB-ve");
        }
        if(ABjRadioButton8.isSelected()){
        req.setBloodGroup("AB+ve");}
        
        req.setStatus("New Request");
        req.setSender(userAccount);
        
        
   Organization org = null;
       for(Network network :system.getNetworkList() ){
           for(Enterprise ent : network.getEnterpriseDirectory().getEnterpriseList()){
                 for (Organization organization : ent.getOrganizationDirectory().getOrganizationList()){
                    if (organization instanceof BloodBankStaffOrganization){
                     org = organization;
                     break;
                     }
                 }
           }
       }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(req);
            userAccount.getWorkQueue().getWorkRequestList().add(req);
            JOptionPane.showMessageDialog(null,"New request processed");
        
       
       }
           //System.out.println(req.getBloodGroup());
        }
        //    CreateBloodSpec(Name, BloodGroup,vol);
        // TODO add your handling code here:
    }//GEN-LAST:event_submitBtnActionPerformed
public void groupbutton(){
   
        ABjRadioButton8.setActionCommand("ABjRadioButton8");
    bg1.add(ABjRadioButton8);
   AjRadioButton2.setActionCommand("AjRadioButton2");
    bg1.add(AjRadioButton2);
    
    BjRadioButton4.setActionCommand("BjRadioButton4");
    bg1.add(BjRadioButton4);
    
    OjRadioButton6.setActionCommand("OjRadioButton6");
    bg1.add(OjRadioButton6);
    
    _ABjRadioButton7.setActionCommand("_ABjRadioButton7");
    bg1.add(_ABjRadioButton7);
    
    _AjRadioButton1.setActionCommand("_AjRadioButton1");
    bg1.add(_AjRadioButton1);
    
    _BjRadioButton3.setActionCommand("_BjRadioButton3");
    bg1.add(_BjRadioButton3);
    
    _OjRadioButton5.setActionCommand("_OjRadioButton5");
    bg1.add(_OjRadioButton5);
   // btnsel = String.valueOf(bg1.getSelection());
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        RequestBlood dwjp = (RequestBlood) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
               
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void _AjRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__AjRadioButton1ActionPerformed
       

        // TODO add your handling code here:
    }//GEN-LAST:event__AjRadioButton1ActionPerformed

    private void AjRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AjRadioButton2ActionPerformed

    private void volTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_volTxtKeyPressed
     // TODO add your handling code here:
    }//GEN-LAST:event_volTxtKeyPressed

    private void volTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_volTxtKeyReleased
     volLabl.setText(""); 
        try{
            int v=Integer.parseInt(volTxt.getText());}
        catch(NumberFormatException e){
              b=false;
              volLabl.setText("Enter a valid integer");
  if(volTxt.getText().trim().isEmpty()){
       volLabl.setText(" Volumefield is empty");
        b=false;;}
            }    // TODO add your handling code here:
    }//GEN-LAST:event_volTxtKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ABjRadioButton8;
    private javax.swing.JRadioButton AjRadioButton2;
    private javax.swing.JRadioButton BjRadioButton4;
    private javax.swing.JRadioButton OjRadioButton6;
    private javax.swing.JRadioButton _ABjRadioButton7;
    private javax.swing.JRadioButton _AjRadioButton1;
    private javax.swing.JRadioButton _BjRadioButton3;
    private javax.swing.JRadioButton _OjRadioButton5;
    private javax.swing.JLabel bldLbl1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton submitBtn;
    private javax.swing.JLabel volLabl;
    private javax.swing.JTextField volTxt;
    // End of variables declaration//GEN-END:variables
}
