/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.VaccineManagerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Vaccine.VaccineInventory;
import Business.Vaccine.VaccineInventoryDirectory;
import Business.VaccineWorkQueue.VaccineWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author nikhi
 */
public class ProcessVaccineRequestJPanel extends javax.swing.JPanel {

     private JPanel userProcessContainer;
    private Organization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;
    private VaccineWorkRequest request;
    private VaccineInventoryDirectory VaccInvDir;
    private Boolean b;
    public ProcessVaccineRequestJPanel(JPanel userProcessContainer, VaccineWorkRequest request, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.organization = organization; //(VaccineInventoryOrganization)
        this.enterprise = enterprise;
        this.userAccount = account;
        this.request = request;
        this.business = business;
        this.VaccInvDir = organization.getVaccineInvDir();
        vnametxt.setText(request.getVaccineName());
        typetxt.setText(request.getVaccineType());
        qreqdtxt.setText(String.valueOf(request.getQty()));
        msgtxt.setText(request.getMessage());
        this.b=true;
       
        for (VaccineInventory vaccine : VaccInvDir.getVaccineStockList())
        {
        if (vaccine.getVaccineName().equals(request.getVaccineName()))
        {
        invstocktxt.setText(String.valueOf(vaccine.getInvStock())); 

        }
        }
        
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        typetxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        vnametxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        qreqdtxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        invstocktxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        msgtxt = new javax.swing.JTextField();
        processBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("VACCINE STOCK REQUEST");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 32, 235, 24));

        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setText("VACCINE TYPE");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 116, 124, 33));

        typetxt.setEnabled(false);
        add(typetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 116, 223, 33));

        jLabel3.setForeground(new java.awt.Color(255, 102, 102));
        jLabel3.setText("VACCINE NAME");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 175, 124, 33));

        vnametxt.setEnabled(false);
        add(vnametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 175, 223, 33));

        jLabel4.setForeground(new java.awt.Color(255, 102, 102));
        jLabel4.setText("QUANTITY REQUIRED");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 234, 124, 33));

        qreqdtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qreqdtxtKeyReleased(evt);
            }
        });
        add(qreqdtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 234, 223, 33));

        jLabel5.setForeground(new java.awt.Color(255, 102, 102));
        jLabel5.setText("INVENTORY STOCK");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 300, 124, 33));

        invstocktxt.setEnabled(false);
        add(invstocktxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 300, 223, 33));

        jLabel6.setForeground(new java.awt.Color(255, 102, 102));
        jLabel6.setText("MESSAGE");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 367, 85, 33));
        add(msgtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 367, 567, 33));

        processBtn.setBackground(new java.awt.Color(255, 102, 102));
        processBtn.setForeground(new java.awt.Color(255, 255, 255));
        processBtn.setText("PROCESS REQUEST");
        processBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processBtnActionPerformed(evt);
            }
        });
        add(processBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 490, -1, 26));

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 490, 72, 26));

        jLabel7.setForeground(new java.awt.Color(255, 102, 102));
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 126, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void processBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processBtnActionPerformed
b=true;

 if(qreqdtxt.getText().trim().isEmpty()){
       jLabel7.setText(" Quantity can't be empty");
        b=false;;}

    if(b){
       request.setMessage(msgtxt.getText());
       request.setQty(Integer.parseInt(qreqdtxt.getText()));
       request.setStatus("Stock Sent");
       
         for (VaccineInventory vaccine : VaccInvDir.getVaccineStockList())
        {
        if (vaccine.getVaccineName().equals(request.getVaccineName()))
        {
         int qty = vaccine.getInvStock() - request.getQty();
         vaccine.setInvStock(qty);

        }
        }
    }
    }//GEN-LAST:event_processBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        VaccineManagerWorkAreaJPanel cmwjp = (VaccineManagerWorkAreaJPanel) component;
        cmwjp.populateTable();
        //cmwjp.populateRequestTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void qreqdtxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qreqdtxtKeyReleased
         jLabel7.setText(""); 
        try{int x=Integer.parseInt(qreqdtxt.getText());
         }
         catch(NumberFormatException e){
             jLabel7.setText("Enter valid number");
             b=false;
         }        // TODO add your handling code here:
    }//GEN-LAST:event_qreqdtxtKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField invstocktxt;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField msgtxt;
    private javax.swing.JButton processBtn;
    private javax.swing.JTextField qreqdtxt;
    private javax.swing.JTextField typetxt;
    private javax.swing.JTextField vnametxt;
    // End of variables declaration//GEN-END:variables
}
